---
- include_vars: 
    name: USERS
    file: "{{playbook_dir}}/vars/users.yaml"
- set_fact: 
    be_user: &be_user
      become: true
      become_user: "{{USERS.MAIN_USER}}"
- name: Install OhMyZsh
  <<: *be_user
  block:
  - name: Get stat OHMYZSH 
    stat:
      path: ~/.oh-my-zsh
    register: oh_my_zsh
  - name: Install OH-MY-ZSH
    when: not (oh_my_zsh.stat.isdir is defined and oh_my_zsh.stat.isdir)
    block:
    - name: Download zsh installer
      get_url: 
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh 
        dest: /tmp/zsh-installer.sh
        mode: '0700'
    - name: Execute the zsh-installer.sh
      shell: CHSH=no RUNZSH=no /tmp/zsh-installer.sh
    - name: Remove the zsh-installer.sh
      file: 
        path: /tmp/zsh-installer.sh 
        state: absent

- name: Create folders
  <<: *be_user
  loop: ["~/dev", "~/tmp"]
  file:
    path: "{{item}}"
    state: directory
- name: dotfiles
  <<: *be_user
  block:
  - name: Check that the ~/.dotfiles exists
    stat:
      path: ~/.dotfiles
    register: dotfiles
  - name: Clone dotfiles repo
    ansible.builtin.git:
      repo: https://github.com/trojaj12/DotFiles.git
      dest: ~/.dotfiles
      track_submodules: true
      recursive: true
    when: not dotfiles.stat.exists


