---
- include_vars: 
    name: USERS
    file: "{{playbook_dir}}/vars/users.yaml"
- set_fact: 
    be_user: &be_user
      become: true
      become_user: "{{USERS.MAIN_USER}}"

- name: Add users
  loop: "{{USERS.LIST}}"
  loop_control:
    label: "{{item.name}}"
  user:
    name: "{{item.name}}"
    generate_ssh_key: "{{ item.ssh if ssh.ssh is defined else False }}"
    password: "{{ item.password | default(item.name) | password_hash('sha512') }}"
    append: yes
    groups: "{{ item.groups | default([]) }}"
    shell: "{{ item.shell if item.shell is defined else '/bin/bash' }}"

- name: Add user to sudoers
  loop: "{{USERS.LIST}}"
  loop_control:
    label: "{{item.name}}"
  when: item.power is defined and item.power is true
  community.general.sudoers:
    name: "{{item.name}}"
    user: "{{item.name}}"
    commands: ALL
    runas: ALL
    nopassword: yes